<?php
/*
  Basic page for my sites.
  1. Header
  2. Three columns
  3. Content
  4. Footer.
  
  Page title and footer content are generated by this php
*/
$title="Test Page";
$dt = date('Y');
$foot = "Copyright &copy; $dt";
//Space fill lorem ipsum text
$latin = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sit amet justo quam, 
non vehicula mauris. Morbi dignissim consequat turpis eu vulputate. In hac habitasse platea 
dictumst. Duis tempor libero sed nisi mattis sodales. Cras et interdum erat. Fusce id enim sem, 
at ultrices felis. Cras porttitor volutpat dapibus. Cras molestie justo id lorem hendrerit tincidunt. 
Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. 
Etiam et eros turpis, ut pharetra magna. Donec odio mi, posuere nec congue sollicitudin, 
tempor feugiat nunc. Ut neque lacus, porttitor at consectetur at, commodo ac lacus.';
?>
<!DOCTYPE HTML>
<html>
<head>
<title><?php echo $title; ?>
<style>
  *{
    border: 0;
    margin: 0;
  }
  body{
    
  }
  .columns{
    width: 31%;
    margin-left: 2px;
    margin-right:2px;
    /*border-right: 1px solid gray;*/
    float: left;
    /*height: 20px;*/
    overflow: auto;
    padding: 5px;
  }
  #wrapper{
    border: 1px solid gray;
    width: 98%;
    /*height: 365px;*/
    margin: 10px auto;
    background-color: #F0F0F0;
    -moz-border-radius: 3px;
  }
  #header{
    width: 100%;
    height: 50px;
    border-bottom: 1px solid gray;
    
  }
  #menubar{
    height: 20px;
    border-top: 1px solid gray;
    text-align: center;
  }
  #content{
    clear: both;
    /*height: 200px;*/
    border-top: 1px solid gray;
  }
  #footer{
    text-align: center;
    height: 15px;
    border-top: 1px solid gray;
    font-size: 10px;
    clear: both;
  }
  input{
    border:1px solid black;
    -moz-border-radius: 3px;

  }
  label{
    display: inline-block;
    text-align: right;
    margin-right: 3px;
    width: 150px;
    font-weight: bold;
    font-size: 12px;
  }
</style>
</head>
<body>
<div id="wrapper">
<div id="header"><h2><?php echo $title ?></h2>
<div id="menubar">Menu</div>
</div>
<div id="left-col" class="columns">About Us:<br/><?php echo $latin ?></div>
<div id="center-col" class="columns">Services:<br/><?php echo $latin ?></div>
<div id="right-col" class="columns">Contacts:<br/><?php echo $latin ?></div>
<div id="content">Sign Up:<br/><!--<?php echo $latin ?>--><br/><br/>
<form id="form1">
<label>Name</label><input type="text" size="40"/><br/>
<label>Address</label><input type="text" size="40"/><br/>
<label>City, State Zip</label><input type="text" size="40"/><br/>
<label>Email</label><input type="text" size="40"/><br/>
<label>Phone</label><input type="text" size="40"/><br/>
<label>Send me your newsletter</label><input type="checkbox"/><br/>
<input style="margin-left: 170px  ;" type="submit" value="Join"/><br/><br/> 
</div> <!-- content -->
</form>

<div id="footer">
<?php echo $foot ?>
</div>
</div> <!-- wrapper -->

</body>
</html>