<?php
file_compress('compressed_css.css',
array('../styles/basestyle.css',
'../styles/truckloader.css',
'../calendar/calendar.css',
'../styles/jquery.autocomplete.css',
'../styles/jquery-ui-1.7.3.custom.css',
'../styles/flexigrid.css',
'../styles/global_search.css',
'../styles/brainjarmenu.css',
'../scripts/tablesorterstyle.css'));
file_compress('compressed_javascript.js',
array("../calendar/setLongDateFormat.js",
"../calendar/calendar.js",
"../scripts/tickler_overlay.js",
"../scripts/zend_reminder_overlay.js",
"../scripts/common.js",
"../scripts/jquery.autocomplete.js",
"../scripts/flexigrid.js",
"../scripts/shortcut.js",
"../scripts/global_search.js",
"../scripts/jquery.scrollTo-1.4.2-min.js",
"../scripts/jquery-ui-1.7.3.custom.min.js",
"../scripts/tablesort.js",
"../scripts/brainjarmenu.js",
"../scripts/jquery.tablesorter.min.js"));
?>

